version: '3.8'
services: 
    # db:
    #     image: postgres:10-alpine
    #     environment:
    #         - POSTGRES_DB=davos
    #         - POSTGRES_USER=postgres
    #         - POSTGRES_PASSWORD=postgres
    #     ports:
    #         - "6543:5432"
    main:
        build: 
            context: .
            dockerfile: Dockerfile
        command: 'php artisan serve --host=0.0.0.0'
        volumes:
            - .:/app
        ports:
            - 8000:8000